version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout

  build:

    docker:
      - image: circleci/node:8.11
    environment:
      CI: false
    working_directory: ~/serverless-stack/notes-app-client
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run:
          command: pwd
          working_directory: notes-app-client
      - run: ls
      - run:
          command: sudo npm install
          working_directory: notes-app-client
      - run:
          command: CI=false npm run build
          environment:
            CI: false
          working_directory: notes-app-client

        # name: Update npm
        # command: 'sudo npm install -g npm@latest'
      # - run:
      #   name: install packages
      #   command: 'sudo npm install'
      # - run:
      #   name: build the assets
      #   command: 'sudo npm run build'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - build
        # requires:
        #   - checkout_code
